version: "3"
services:
  diginext-framework:
    build:
      context: .
      dockerfile: deployment/Dockerfile
      args:
        NEXT_PUBLIC_ENV: development
        NEXT_PUBLIC_API_BASE_PATH: https://api.the-lab-2020.zii.vn
        BACKEND_DOMAIN: https://api.the-lab-2020.zii.vn
      # dockerfile: deployment/dev.Dockerfile
    # volumes:
      # - .:/usr/app
    ports:
      - 3000:3000
    environment:
      # - NEXT_PUBLIC_ENV=development
      # - NEXT_PUBLIC_API_BASE_PATH=https://api.the-lab-2020.zii.vn
      # - NEXT_PUBLIC_CDN_BASE_PATH=https://cdn.digitop.vn
      - BACKEND_DOMAIN=https://api.the-lab-2020.zii.vn
      - SOME_SECRET_KEY=987b3k5bj34bnhj5